-- reclassify_semiconductor_extra_rollback.sql
-- reclassify_semiconductor_extra.sql 실행 전 sub_industry 로 원복 (129종목, industry는 반도체 유지)
BEGIN;
UPDATE companies SET sub_industry=NULL WHERE code='032580'; -- 피델릭스
UPDATE companies SET sub_industry='검사장비' WHERE code='348210'; -- 넥스틴
UPDATE companies SET sub_industry=NULL WHERE code='083310'; -- 엘오티베큠
UPDATE companies SET sub_industry='냉각' WHERE code='036200'; -- 유니셈
UPDATE companies SET sub_industry=NULL WHERE code='141000'; -- 비아트론
UPDATE companies SET sub_industry=NULL WHERE code='040910'; -- 아이씨디
UPDATE companies SET sub_industry='검사장비' WHERE code='322310'; -- 오로스테크놀로지
UPDATE companies SET sub_industry=NULL WHERE code='417840'; -- 저스템
UPDATE companies SET sub_industry='장비' WHERE code='079370'; -- 제우스
UPDATE companies SET sub_industry=NULL WHERE code='122640'; -- 예스티
UPDATE companies SET sub_industry=NULL WHERE code='049080'; -- 기가레인
UPDATE companies SET sub_industry='광반도체' WHERE code='071280'; -- 로체시스템즈
UPDATE companies SET sub_industry='후공정-장비' WHERE code='199550'; -- 레이저옵텍
UPDATE companies SET sub_industry='냉각' WHERE code='083450'; -- GST
UPDATE companies SET sub_industry='HBM장비' WHERE code='039440'; -- 에스티아이
UPDATE companies SET sub_industry='소재' WHERE code='030530'; -- 원익홀딩스
UPDATE companies SET sub_industry=NULL WHERE code='060310'; -- 3S
UPDATE companies SET sub_industry=NULL WHERE code='037350'; -- 성도이엔지
UPDATE companies SET sub_industry=NULL WHERE code='011930'; -- 신성이엔지
UPDATE companies SET sub_industry=NULL WHERE code='010400'; -- 우진아이엔에스
UPDATE companies SET sub_industry=NULL WHERE code='045100'; -- 한양이엔지
UPDATE companies SET sub_industry=NULL WHERE code='212710'; -- 아이에스티이
UPDATE companies SET sub_industry=NULL WHERE code='025560'; -- 미래산업
UPDATE companies SET sub_industry='테스터' WHERE code='086390'; -- 유니테스트
UPDATE companies SET sub_industry=NULL WHERE code='217190'; -- 제너셈
UPDATE companies SET sub_industry=NULL WHERE code='089790'; -- 제이티
UPDATE companies SET sub_industry=NULL WHERE code='089890'; -- 코세스
UPDATE companies SET sub_industry='검사장비' WHERE code='168360'; -- 펨트론
UPDATE companies SET sub_industry='레이저' WHERE code='452190'; -- 한빛레이저
UPDATE companies SET sub_industry='프로브' WHERE code='412350'; -- 레이저쎌
UPDATE companies SET sub_industry=NULL WHERE code='217500'; -- 러셀
UPDATE companies SET sub_industry=NULL WHERE code='140070'; -- 서플러스글로벌
UPDATE companies SET sub_industry=NULL WHERE code='045300'; -- 성우테크론
UPDATE companies SET sub_industry=NULL WHERE code='088280'; -- 쏘닉스
UPDATE companies SET sub_industry='광반도체' WHERE code='078150'; -- HB테크놀러지
UPDATE companies SET sub_industry=NULL WHERE code='321260'; -- 프로이천
UPDATE companies SET sub_industry=NULL WHERE code='224060'; -- 더코디
UPDATE companies SET sub_industry=NULL WHERE code='036090'; -- 위지트
UPDATE companies SET sub_industry='소켓' WHERE code='098120'; -- 마이크로컨텍솔
UPDATE companies SET sub_industry=NULL WHERE code='080580'; -- 오킨스전자
UPDATE companies SET sub_industry=NULL WHERE code='271830'; -- 팸텍
UPDATE companies SET sub_industry='본딩와이어' WHERE code='033160'; -- 엠케이전자
UPDATE companies SET sub_industry=NULL WHERE code='077360'; -- 덕산하이메탈
UPDATE companies SET sub_industry=NULL WHERE code='146320'; -- 비씨엔씨
UPDATE companies SET sub_industry='파츠/쿼츠' WHERE code='272110'; -- 케이엔제이
UPDATE companies SET sub_industry='부품' WHERE code='183300'; -- 코미코
UPDATE companies SET sub_industry='부품' WHERE code='195870'; -- 해성디에스
UPDATE companies SET sub_industry=NULL WHERE code='424980'; -- 마이크로투나노
UPDATE companies SET sub_industry=NULL WHERE code='147760'; -- 피엠티
UPDATE companies SET sub_industry=NULL WHERE code='059090'; -- 미코
UPDATE companies SET sub_industry='소재' WHERE code='086670'; -- 비엠티
UPDATE companies SET sub_industry='후공정' WHERE code='285490'; -- 노바텍
UPDATE companies SET sub_industry='소재' WHERE code='083500'; -- 에프엔에스테크
UPDATE companies SET sub_industry='소재' WHERE code='114810'; -- 한솔아이원스
UPDATE companies SET sub_industry='부품' WHERE code='009780'; -- 엠에스씨
UPDATE companies SET sub_industry=NULL WHERE code='355150'; -- 코스텍시스
UPDATE companies SET sub_industry=NULL WHERE code='017900'; -- 광전자
UPDATE companies SET sub_industry='광반도체' WHERE code='327260'; -- RF머트리얼즈
UPDATE companies SET sub_industry=NULL WHERE code='080520'; -- 오디텍
UPDATE companies SET sub_industry=NULL WHERE code='066310'; -- 큐에스아이
UPDATE companies SET sub_industry=NULL WHERE code='046970'; -- 우리로
UPDATE companies SET sub_industry='SSD' WHERE code='009470'; -- 삼화전기
UPDATE companies SET sub_industry='SSD' WHERE code='078350'; -- 한양디지텍
UPDATE companies SET sub_industry=NULL WHERE code='254490'; -- 미래반도체
UPDATE companies SET sub_industry=NULL WHERE code='093520'; -- 매커스
UPDATE companies SET sub_industry=NULL WHERE code='031330'; -- 에스에이엠티
UPDATE companies SET sub_industry=NULL WHERE code='077500'; -- 유니퀘스트
UPDATE companies SET sub_industry=NULL WHERE code='142210'; -- 유니트론텍
UPDATE companies SET sub_industry=NULL WHERE code='256630'; -- 포인트엔지니어링
UPDATE companies SET sub_industry='소재' WHERE code='317330'; -- 덕산테코피아
UPDATE companies SET sub_industry=NULL WHERE code='092070'; -- 디엔에프
UPDATE companies SET sub_industry=NULL WHERE code='171010'; -- 램테크놀러지
UPDATE companies SET sub_industry=NULL WHERE code='241770'; -- 메카로
UPDATE companies SET sub_industry=NULL WHERE code='482630'; -- 삼양엔씨켐
UPDATE companies SET sub_industry='소재' WHERE code='178920'; -- PI첨단소재
UPDATE companies SET sub_industry=NULL WHERE code='489500'; -- 엘케이켐
UPDATE companies SET sub_industry=NULL WHERE code='170920'; -- 엘티씨
UPDATE companies SET sub_industry=NULL WHERE code='251370'; -- 와이엠티
UPDATE companies SET sub_industry=NULL WHERE code='417500'; -- 제이아이테크
UPDATE companies SET sub_industry='소재' WHERE code='425040'; -- 티이엠씨
UPDATE companies SET sub_industry=NULL WHERE code='241790'; -- 티이엠씨씨엔에스
UPDATE companies SET sub_industry=NULL WHERE code='445180'; -- 퓨릿
UPDATE companies SET sub_industry='소재' WHERE code='089980'; -- 상아프론테크
UPDATE companies SET sub_industry='소재' WHERE code='036830'; -- 솔브레인홀딩스
UPDATE companies SET sub_industry=NULL WHERE code='402490'; -- 그린리소스
UPDATE companies SET sub_industry=NULL WHERE code='453860'; -- 에이에스텍
UPDATE companies SET sub_industry=NULL WHERE code='008060'; -- 대덕
UPDATE companies SET sub_industry=NULL WHERE code='036710'; -- 심텍홀딩스
UPDATE companies SET sub_industry='MLCC' WHERE code='001820'; -- 삼화콘덴서공업
UPDATE companies SET sub_industry='MLCC' WHERE code='126730'; -- 코칩
UPDATE companies SET sub_industry=NULL WHERE code='036010'; -- 아비코전자
UPDATE companies SET sub_industry='PCB' WHERE code='090460'; -- 비에이치
UPDATE companies SET sub_industry='OSAT' WHERE code='061970'; -- LB세미콘
UPDATE companies SET sub_industry='테스터' WHERE code='330860'; -- 네패스아크
UPDATE companies SET sub_industry=NULL WHERE code='033170'; -- 시그네틱스
UPDATE companies SET sub_industry=NULL WHERE code='097800'; -- 윈팩
UPDATE companies SET sub_industry=NULL WHERE code='172670'; -- 에이엘티
UPDATE companies SET sub_industry=NULL WHERE code='405100'; -- 큐알티
UPDATE companies SET sub_industry=NULL WHERE code='119830'; -- 아이텍
UPDATE companies SET sub_industry=NULL WHERE code='011690'; -- 와이투솔루션
UPDATE companies SET sub_industry=NULL WHERE code='396270'; -- 넥스트칩
UPDATE companies SET sub_industry=NULL WHERE code='094170'; -- 동운아나텍
UPDATE companies SET sub_industry=NULL WHERE code='317120'; -- 라닉스
UPDATE companies SET sub_industry=NULL WHERE code='177900'; -- 쓰리에이로직스
UPDATE companies SET sub_industry=NULL WHERE code='123860'; -- 아나패스
UPDATE companies SET sub_industry=NULL WHERE code='456010'; -- 아이씨티케이
UPDATE companies SET sub_industry=NULL WHERE code='052860'; -- 아이앤씨
UPDATE companies SET sub_industry=NULL WHERE code='464500'; -- 아이언디바이스
UPDATE companies SET sub_industry=NULL WHERE code='038880'; -- 아이에이
UPDATE companies SET sub_industry=NULL WHERE code='059120'; -- 아진엑스텍
UPDATE companies SET sub_industry=NULL WHERE code='096610'; -- 알에프세미
UPDATE companies SET sub_industry=NULL WHERE code='117670'; -- 알파칩스
UPDATE companies SET sub_industry=NULL WHERE code='092600'; -- 앤씨앤
UPDATE companies SET sub_industry='팹리스' WHERE code='102120'; -- 어보브반도체
UPDATE companies SET sub_industry=NULL WHERE code='096870'; -- 엘디티
UPDATE companies SET sub_industry=NULL WHERE code='115610'; -- 이미지스
UPDATE companies SET sub_industry=NULL WHERE code='389020'; -- 자람테크놀로지
UPDATE companies SET sub_industry=NULL WHERE code='303030'; -- 지니틱스
UPDATE companies SET sub_industry='팹리스' WHERE code='054450'; -- 텔레칩스
UPDATE companies SET sub_industry=NULL WHERE code='365590'; -- 하이딥
UPDATE companies SET sub_industry=NULL WHERE code='452430'; -- 사피엔반도체
UPDATE companies SET sub_industry=NULL WHERE code='289930'; -- 웨이비스
UPDATE companies SET sub_industry=NULL WHERE code='429270'; -- 시지트로닉스
UPDATE companies SET sub_industry=NULL WHERE code='101400'; -- 엔시트론
UPDATE companies SET sub_industry=NULL WHERE code='226590'; -- 엠디바이스
UPDATE companies SET sub_industry='디자인하우스' WHERE code='445090'; -- 에이직랜드
UPDATE companies SET sub_industry=NULL WHERE code='490470'; -- 세미파이브
UPDATE companies SET sub_industry=NULL WHERE code='045970'; -- 코아시아
UPDATE companies SET sub_industry=NULL WHERE code='234030'; -- 싸이닉솔루션
COMMIT;
